server:
  port: 3000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dapenbi
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true